//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.28 at 12:21:59 PM EET 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for alpha complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="alpha">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="starName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numberId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "alpha", propOrder = {
    "starName",
    "numberId"
})
public class Alpha {

    @XmlElement(required = true)
    protected String starName;
    protected int numberId;

    /**
     * Gets the value of the starName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStarName() {
        return starName;
    }

    /**
     * Sets the value of the starName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStarName(String value) {
        this.starName = value;
    }

    /**
     * Gets the value of the numberId property.
     * 
     */
    public int getNumberId() {
        return numberId;
    }

    /**
     * Sets the value of the numberId property.
     * 
     */
    public void setNumberId(int value) {
        this.numberId = value;
    }

}
