//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.28 at 12:21:59 PM EET 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetConstellationRequest }
     * 
     */
    public GetConstellationRequest createGetConstellationRequest() {
        return new GetConstellationRequest();
    }

    /**
     * Create an instance of {@link GetConstellationResponse }
     * 
     */
    public GetConstellationResponse createGetConstellationResponse() {
        return new GetConstellationResponse();
    }

    /**
     * Create an instance of {@link Constellation }
     * 
     */
    public Constellation createConstellation() {
        return new Constellation();
    }

    /**
     * Create an instance of {@link DeleteConstellationRequest }
     * 
     */
    public DeleteConstellationRequest createDeleteConstellationRequest() {
        return new DeleteConstellationRequest();
    }

    /**
     * Create an instance of {@link PostConstellationRequest }
     * 
     */
    public PostConstellationRequest createPostConstellationRequest() {
        return new PostConstellationRequest();
    }

    /**
     * Create an instance of {@link Alpha }
     * 
     */
    public Alpha createAlpha() {
        return new Alpha();
    }

}
